### ISSUE TITLE
"Unable to get page count. Is poppler installed and in PATH?"

### ISSUE THREAD

**Issue by zyc130130** [jeylabs/aws-lambda-poppler-layer#6]
Hi, i have add the aws-lambda-poppler-layer zip file into my aws lambda lay, but i have the problem "Unable to get page count. Is poppler installed and in PATH?" my code use the arg as "poppler_path=r"/opt/bin/",", and i'm sure the poppler_path is correct. What's happen?

**Comment by pavinthan** [comment]
@zyc130130 the binary path is `/opt/bin/pdfinfo` will give you the page counts, have you try https://github.com/jeylabs/aws-lambda-poppler ?

**Comment by jafar-albadarneh** [comment]
@pavinthan I think there is a real issue here! I've tried to compile and build the docker image from scratch and imported the zip layer into lambda. still getting the `Unable to get page count. Is poppler installed and in PATH?` exception.
Spent more than 5 hours trying to get it running with no luck!

Just to mention, i did passes the path explicitly `convert_from_bytes(data, output_folder=output_path, poppler_path = "/opt/bin/")` without luck!

I'd appreciate your help on this!
